# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iFlat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iFlat
  pod ‘Firebase/Core’
  pod ‘Firebase/Database’
  pod ‘Firebase/Auth’
  pod 'Firebase/Storage'
  pod 'Kingfisher', '~> 3.0'
  pod 'JTAppleCalendar', '~> 6.0'

  target 'iFlatTests' do

    # Pods for testing
  end

  target 'iFlatUITests' do
    # Pods for testing
  end

end
